### ISSUE TITLE
segfault in AlleleParser with 1.1.0 SeqLib development version

### ISSUE THREAD

**Issue by chapmanb** [ekg/freebayes#364]
I'm running the lighterweight SeqLib fork from @walaj (PR #338) that builds cleanly on OSX and running into an issue. Here's is a reproducible test case:

https://s3.amazonaws.com/chapmanb/testcases/fb_allele_segfault.tar.gz

That exits with a string index error:
```
alignment: HS20_09413:8:1311:3352:83704
alignment: HS20_09413:8:1311:12434:81100
alignment: HS20_09413:8:1311:21344:58394
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at
```
In a debugger, it looks like it's unhappy when parsing an alignment:
```
Program received signal SIGABRT, Aborted.
(gdb) bt
#0  0x00007ffff6de5c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6de9028 in __GI_abort () at abort.c:89
#2  0x00007ffff76efb05 in __gnu_cxx::__verbose_terminate_handler() () from /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libstdc++.so.6
#3  0x00007ffff76edca6 in ?? () from /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libstdc++.so.6
#4  0x00007ffff76edcd3 in std::terminate() () from /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libstdc++.so.6
#5  0x00007ffff76edef2 in __cxa_throw () from /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libstdc++.so.6
#6  0x00007ffff7743197 in std::__throw_out_of_range(char const*) () from /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libstdc++.so.6
#7  0x00007ffff774d3aa in std::string::at(unsigned long) () from /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libstdc++.so.6
#8  0x0000000000464b52 in AlleleParser::registerAlignment(SeqLib::BamRecord&, RegisteredAlignment&, std::string&, std::string&) ()
#9  0x0000000000467932 in AlleleParser::updateAlignmentQueue(long, std::vector<Allele*, std::allocator<Allele*> >&, bool) ()
#10 0x000000000046f8e6 in AlleleParser::getPartialObservationsOfHaplotype(Samples&, int, std::vector<Allele*, std::allocator<Allele*> >&) ()
#11 0x000000000046dbbe in AlleleParser::buildHaplotypeAlleles(std::vector<Allele, std::allocator<Allele> >&, Samples&, std::map<std::string, std::vector<Allele*, std::allocator<Allele*> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<Allele*, std::allocator<Allele*> > > > >&, std::map<std::string, std::vector<Allele*, std::allocator<Allele*> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<Allele*, std::allocator<Allele*> > > > >&, std::map<Allele*, std::set<Allele*, std::less<Allele*>, std::allocator<Allele*> >, std::less<Allele*>, std::allocator<std::pair<Allele* const, std::set<Allele*, std::less<Allele*>, std::allocator<Allele*> > > > >&, int) ()
#12 0x0000000000409dd2 in main ()
```
This works correctly in the 1.1.0 release so is something to help clean up #338 for more widespread use before pulling that in. Happy to provide any other info that would help and thanks for looking into the issue.

**Comment by walaj** [comment]
Good catch and thanks for the easy-to-recreate example. The issue was an over-aggressive check for empty quality strings that quit early for a 0 quality score (i.e. "!"). I just commented out those two lines.

I updated SeqLib and the PR freebayes branch to handle this. It works on the provided example.

**Comment by chapmanb** [comment]
Jeremiah;
Thanks so much for the quick fix. I updated the bioconda recipe with this update, much appreciated.
